### ISSUE TITLE
Choisir nom pour la boutique

### ISSUE THREAD

**Issue by AlexandrePuiseux65** [Alexios76/PT2-S2-G7#1]

**Comment by AlexandrePuiseux65** [comment]
appareil photo

**Comment by AlexandrePuiseux65** [comment]
Liens : https://image.lexica.art/full_jpg/07a3a750-263c-4bb1-acab-0f277887c423

**Comment by AlexandrePuiseux65** [comment]
https://image.lexica.art/full_jpg/4d2eaaa8-f64a-4d74-acc5-dc6d0024eedf

Liens image

**Comment by AlexandrePuiseux65** [comment]
https://media.istockphoto.com/id/1152862876/fr/vectoriel/appareil-photo-ic%C3%B4ne-plat-de-photographie-pixel-parfait-pour-mobile-et-web.jpg?s=612x612&w=0&k=20&c=HbqdD6yfVXQ9lmZKTi1jk2OjMjEHzgnzJnGtyYCLRds=

Logo 1

**Comment by MartinCharpentier92** [comment]
Potentiel logo : https://image.lexica.art/full_jpg/f95d3dd1-1189-4f8f-83ee-15ef20eaa5f9

**Comment by MartinCharpentier92** [comment]
Potentiel palette : https://colorhunt.co/palette/404258474e6850577a6b728e

**Comment by AlexandrePuiseux65** [comment]
Palette final

**Comment by AlexandrePuiseux65** [comment]
https://colorhunt.co/palette/d8d2ceada7a378707093c7b6
